services:
  - type: web
    name: edutrack-backend
    env: node
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
